---
include:
  - board: lemon_wireless
    shield: skree_left
    snippet: zmk-usb-logging;studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: lemon_wireless
    shield: skree_right vik_pmw3610
