---
include:
  - board: cosmos_lemon_wireless
    shield: rickball_left
  - board: cosmos_lemon_wireless
    shield: rickball_right vik_pmw3610
    snippet: zmk-usb-logging;studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
